### ISSUE TITLE
Unable to install system via system.json

### ISSUE THREAD

**Issue by leafreynolds** [mjording/marvel-multiverse#23]
Associated set of errors:
![image](https://github.com/mjording/marvel-multiverse/assets/80794784/1573ea51-8a39-4f52-aec0-7578906a40f0)

At least one error is related to the targeted zip in json not being set:
![image](https://github.com/mjording/marvel-multiverse/assets/80794784/8c16b41c-0906-4c2e-a6fe-38babeb67195)

Thanks :)

**Comment by super-ben** [comment]
There is no release for the module currently (at all), so at this point, it cannot be installed. I’m eagerly waiting for it. :)

**Comment by rodrigosinistro** [comment]
Hi @mjording 

This project will be launched? I will love play this system on Foundry. I'm waiting for this. 

Thanks
