### ISSUE TITLE
Portrait too large for sheet

### ISSUE THREAD

**Issue by klatub** [mjording/marvel-multiverse#24]
In the attached screen shot the actors portrait is too large.  The other elements on the page overlap the image, the same is happening on "Biography", "Items" and "Effects".

<img width="523" alt="Actor Sheet issue" src="https://github.com/mjording/marvel-multiverse/assets/56140689/d679ccde-c6db-40c8-9e3f-b309ae501e81">

**Comment by mjording** [comment]
that was intentional to give an element of style,  in my example characters (coming soon) I have action portraits that looked good spilling under the stats. I may make a change.
