### ISSUE TITLE
Effects for Powers

### ISSUE THREAD

**Issue by NerdEyeIndustries** [mjording/marvel-multiverse#27]
There's no effect tab for powers... 

While we just have to track it narratively now, if powers had a standard effects tab/functionality we could modify character attributes per the power.. example:

Speed Run 1: Multiply the character's regular Run Speed by their rank to get their new Run Speed. Outside of combat, they can move three times as fast.

Because there's no effects tab, there's no way to alter the character's run speed per the power.

Thanks!

**Comment by mjording** [comment]
Fixed some auto-calculation for powers and added a usable effect tab for editing and adding effects.
