### ISSUE TITLE
Damage is calculated incorrectly according to the Core Rules Book...

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#30]
According to the Marvel Multiverse Core Rule Book (Page 33), damage is calculated as follows:

"When a character deals damage with an action check- like with a close attack or a ranged attack-that damage is expressed as a multiplier applied to the action check's **Marvel die**. To that, you then add the ability the character used for the action check.
A character's basic damage multiplier is their rank, but some powers-hike Mighty or Accuracy-can add to it. These may give a character a bonus to their damage multiplier for certain types of attacks and should be kept track of separately There's space for this on the character sheet.

Example: She-Hulk is Rank 4, so her damage multiplier is "4". Her power Mighty 4 adds +4 to that for those attacks, which gives her a damage multiplier of "8". To that, she adds her Melee score so when she hits with a close attack, she does (dMarvel x 8)+5 points of damage."

In your system implementation, when you roll the "damage roll" at the bottom left of the sheet it adds **all three** of the dice together and multiplies that total by the character rank, instead of just multiplying the Marvel die by the character rank.
However, this "damage roll" also raises another issue that contradicts what the rule book states: The initial action check die roll is also the roll used to determine damage...the Marvel Die in the action check roll is used to calculate the damage, you do *not* roll the 616 die set again for damage.

**Comment by PascalMueller1988** [comment]
The damage multiplier is also not sensitive to size which could result in changes to the multiplier for melee attacks.

Example: 
A sentinel is gigantic sized and rank 4. This means that it's base melee damage multiplier should be 8 (rank 4 + size modifier 4) unless it were to have another power that provides an even greater damage modifier.

**Comment by mjording** [comment]
Thanks for the catch.
