### ISSUE TITLE
Provide user-setable Maximum & Current values for Health and Focus stats...

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#31]
There appears to be some weird things going on when you apply damage to an actors health and/or Focus values: the Token Bars that show the current/max Health and Focus will sometimes set the max bar value to the current bar value when you open the actor sheet. 

I assume that the max Health and Focus are auto-calculated by the game, or are they set simply by the single value you enter into their respective boxes? It would make things easier/clearer/less-prone-to-issues to have separate max and current values that the player/GM can set for these two values...that would also allow for custom values that do not follow the rules exactly if the values are auto-generated or auto-corrected by the system.

Thanks!

**Comment by mjording** [comment]
Yes, max values are not implemented correctly. Marked as a bug to fix.
