### ISSUE TITLE
Character size is not changeable, leading to incorrect Defense Scores, Damage Multipliers, Speeds and Token Sizes

### ISSUE THREAD

**Issue by PascalMueller1988** [mjording/marvel-multiverse#32]
There currently is no option to change character size.

According to the Marvel Multiverse Core Rule Book p.39 & p.73 character size can change Speeds, Token Sizes, Melee & Agility defense scores as well as Melee damage multipliers.

Example:
A sentinel is gigantic sized and rank 4. 

- The melee damage multiplier should be 8 (rank 4 + size modifier 4) unless it were to have another power that provides an even greater damage modifier.
- The melee and agility defense scores should be modified by -3.
- The speeds should be multiplied by the size multiplier of 20
- The token size should be 20 * 20

**Comment by mjording** [comment]
The only size change supported currently is Big. I'll mark this up and should have it fixed soon.

**Comment by PascalMueller1988** [comment]
Amazing, thank you!
