### ISSUE TITLE
Compendium entries can't be copied over

### ISSUE THREAD

**Issue by PascalMueller1988** [mjording/marvel-multiverse#34]
Trying to copy the compendium entries causes this error:

MarvelMultiverseItem validation errors:_stats: compendiumSource: Invalid document ID "" [Detected 1 package: system:marvel-multiverse(1.5.7)]

**Comment by mjording** [comment]
Just to confirm, this is happening while [Importing Single Documents From a Compendium](https://foundryvtt.com/article/compendium/).

**Comment by PascalMueller1988** [comment]
Happens when I try to import single documents from the Compendium tab or an entire folder.

**Comment by mjording** [comment]
I'll need to determine what rules the uuids I'm using are violating, and re-id the compendium. 

You can in the near term drag and drop any compendium item to a character sheet.

**Comment by Nimda99** [comment]
If you create a new Compendium with the same names and copy them across they can then all be imported.  Essentially creating a new compendium.  Slower for traits etc , but Powers are quick as they are all in folders so quick to drag across.

Work around until new compendium/fix arrives.
