### ISSUE TITLE
Power Effects

### ISSUE THREAD

**Issue by NerdEyeIndustries** [mjording/marvel-multiverse#38]
These aren't calculating values.. See Speed Run 1. When you add the power, it changes the character run speed to zero.

Can we get an explanation on how to set these values? You've got calc, noncom, and value? how to force a value for example?

**Comment by mjording** [comment]
Each power has an effects tab on which you should be able to change the value from the power. Speed run 1 should be applying an effect that calculates speed based on rank (via the calc field). You can also directly apply to the value. 

I'll confirm that Speed run 1 is misbehaving and file a bug.

**Comment by mjording** [comment]
Issue affects the origin Alien: Brood, Flight 1, Speed Run 1, Speed Run 2, and Speed Swim. 
The way movement is calculated against rank is broken.
