### ISSUE TITLE
Bug: Damage roll uses pre-edge/trouble value for marvel die...v1.6.7

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#43]
If you add Edge or Trouble to an action check and then roll Damage, the marvel die is treated as if it were the pre-edge/trouble value instead of the new value.

See the attached screenshots for examples:

![error01](https://github.com/user-attachments/assets/ac0421cd-00a3-4e2a-955e-c62e147215f8)

![error02](https://github.com/user-attachments/assets/5cc0cc30-027d-4eaf-b4a5-bbeedb7f4a95)

Thanks!

**Comment by mjording** [comment]
Good catch, looks like an easy fix.
