### ISSUE TITLE
All Movement speeds set to '0" on some Actors after updating to v1.6.9...

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#44]
All Movement speeds set to '0" on some actors after updating to v1.6.9...

Below is a screenshot of the move stats for a couple of random actors from my game showing this issue:

![Untitled](https://github.com/user-attachments/assets/9ccb0708-274a-4263-8e6c-8714bbebb87b)

This only affects **SOME** actors, not all actors. I have no idea why some show 0 speeds and others are ok...they were all created before I updated the game.

**Comment by mjording** [comment]
It could be a migration issue, I did recently make a good deal of changes to size and speed over the last few releases.
Will look into instituting a migration system soon. Until then I'll see if I can reproduce.

**Comment by WildBillLives** [comment]
From an (admittedly) quick look it appears that actors who had powers that affected movement were ok after I updated, those who had the default speed were the ones who went to the zero movement rates...

**Comment by mjording** [comment]
Good to know, I'm guessing if you changed the character size and then reverted it may help.

**Comment by WildBillLives** [comment]
I tried that already but it did not help...I simply created a new trait called "Move_Fix" that manually resets all the speeds back to human default thru active effects for all those with no movement powers.

**Comment by WildBillLives** [comment]
Also...when i dropped the Big trait in and removed it, it still left the +1 to move and -1 to Melee & Agility defenses on the character...so not a recommended thing to do...lol

**Comment by PascalMueller1988** [comment]
Just to validate. This has happened to me, too!

On a side note. What is the @ for run speed? Is there a list of all the attribute names somewhere?

**Comment by WildBillLives** [comment]
> Just to validate. This has happened to me, too!
> 
> On a side note. What is the @ for run speed? Is there a list of all the attribute names somewhere?

" system.movement.run.value " is the run speed value.

**Comment by mjording** [comment]
Hmm, just to be clear this is happening to legacy characters that were migrated poorly, and not new characters.
Aside from building proper migrations going forward the best advice may be to recreate.

**Comment by mjording** [comment]
Yeah, this is no fun, I have a bunch of characters that need to be migrated or recreated. I've tried a couple of ways to automate the migration, but no love.

**Comment by mjording** [comment]
This doesn't seem to have a solution. The fundamental schema for character sheets changed and I didn't account for the impact on existing characters. 

From now on for major data changes, I'll build a migration, and alert users if there is an impacting non-reverse compatible change.
