### ISSUE TITLE
Bug: Re-rolling Marvel Die multiple times adds multiple dice together for damage. (v1.7.1)

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#46]
_Release v1.7.1 issue:_
If you re-roll (i.e. use Edge on) the Marvel die in a check multiple times, and then roll the Damage, sometimes more than one of the Marvel die rolls are added together to calculate the damage instead of just the **single highest roll** as intended. 

See the following screenshot for an example:

![example](https://github.com/user-attachments/assets/c7b102a1-364a-4019-9c38-949072ecaacf)

**Comment by mjording** [comment]
Are there legit cases for that many edges?

**Comment by WildBillLives** [comment]
Well, I've had a player spend 3 Karma for Edge on one check to disarm an atomic bomb in downtown Manhattan in my game...

**Comment by mjording** [comment]
I suppose that will happen.
Is there a limit to how many edges one die can have?

**Comment by WildBillLives** [comment]
> I suppose that will happen. Is there a limit to how many edges one die can have?

Not according to the Rules-as-Written ASAIK.

**Comment by mjording** [comment]
Did some correction on this. 
May file an issue to handle switching between edge rolls and trouble. Also rolling multiple troubles with a fantastic roll is an issue.
