### ISSUE TITLE
Bug: Marvel die rolling "M" not counting as a 6 for re-rolls (v1.7.1)

### ISSUE THREAD

**Issue by WildBillLives** [mjording/marvel-multiverse#47]
When the Marvel die rolls a Fantastic Success (an "M" result) when using an Edge (i.e. a reroll) it is supposed to count as a "6" , but the roll system in the game is counting it as a "1". 

_Core Rules, page 12: If your Marvel die comes up with a Marvel logo, that's a Fantastic result. Count the Marvel die as a 6 instead of a 1 and then add up the numbers like usual._

Here is an example of this from my game: 

![example 02](https://github.com/user-attachments/assets/773799e8-11e9-4d15-af66-87242e8af879)

Edit: _It appears this example also suffers from the same issue I reported in my previous bug report (Issue #46) - rerolls of the Marvel die are being added to the total...in the above example the total value says "10', which could only be because both marvel die rolls of "2" and "1" (which should actually count as a "6" since its the 'M' result) are being added to the total._

**Comment by mjording** [comment]
The Damage text shows the marvel die being counted as 2, so rerolls aren't respecting the M as 6 but roll seems to be. Regardless behavioirs wrong, I'll look into it.

**Comment by mjording** [comment]
The kh modifier on the roll is not reading fantastic results as the highest result.
