### ISSUE TITLE
NPC sheet don't works

### ISSUE THREAD

**Issue by LayonRodrigues** [mjording/marvel-multiverse#58]
![image](https://github.com/user-attachments/assets/6fc1fc10-eae3-438a-b55f-c827bbe63426)
Error in movement and attribute calculation.

**Comment by mjording** [comment]
This is a known issue. 
I've been using character sheets for NPCs which the books seem to due with the exception of Henchmen. 

There are existing tickets calling for the creation of NPC and vehicle sheets #56 and #53 
I'll mark this as a bug and work on it along-side #56.

The books NPC sheets are fairly light see attached image 
![image](https://github.com/user-attachments/assets/dc2bec11-48b0-4656-9be2-c588781b0ac5)

Is that enough game info (no movement stats, etc) or do we need to expose more data?

**Comment by LayonRodrigues** [comment]
I agree with you. Perhaps a specific part to configure attacks below the layout (when the item: Weapons is functional).

If you need any help with design, CSS or anything I can help with, I'm at your disposal.

I've been helping with the development of other (unofficial) Foundry systems for a few years now (almost since Foundry was launched).

**Comment by mjording** [comment]
Thanks, I appreciate the office. 
If you have a good design idea fork the repo and send your proposed style over on a PR.
