### ISSUE TITLE
[bug] Battle Ready trait

### ISSUE THREAD

**Issue by magohuman** [mjording/marvel-multiverse#63]
Hi, I noticed that when I add the Battle Ready trait, the focus value is automatically set and can't be changed afterward. Every time you reopen the sheet (or change other value, like health or an ability), the focus value reverts to what it was previously (previous value +30). While you can adjust the max and current focus values, they always reset.

Thank you

**Comment by mjording** [comment]
In Battle Ready there is an effect named 'extra focus', you can edit the effects currently.  I'm going to remove the effect change to focus value but keep the change to focus max. Max will reset which seems reasonable, I don't know any situation where max is changed during gameplay. 

You should delete and re-add battle ready  to your character on the next release. 1.7.9
