### ISSUE TITLE
Attacks don't trigger the Sequence Automated Animation module

### ISSUE THREAD

**Issue by LayonRodrigues** [mjording/marvel-multiverse#65]
Attacks don't trigger the Sequencer -  Automated Animation module.

**Comment by mjording** [comment]
The [Automated Animation Module](https://foundryvtt.com/packages/autoanimations) is not actively supported, [according to its github page](https://github.com/otigon/automated-jb2a-animations). I'll attempt to determine the underlying issue and if its a deprecation issue with the module.

**Comment by mjording** [comment]
Taking this on in #71 #72.
