### ISSUE TITLE
[Issue] Characters cannot go over their max focus value

### ISSUE THREAD

**Issue by PascalMueller1988** [mjording/marvel-multiverse#66]
Currently characters cannot store more than their max focus value but at least one power (Energy Absorption) is intended to allow characters to do so.

**Comment by PascalMueller1988** [comment]
Actually correction: Seems that I can enter values above maximum on the character sheet and it's not just possible via the token.

**Comment by mjording** [comment]
Ok, I haven't gotten into the token actions that much. Going to close this. Feel free to file a new issue for the token action, but I think thats the default behavior.
